// react/src/components/List/List.tsx
import { ReactNode } from "react";
import cn from "classnames";
import css from "./List.module.css";

export type ListProps<T> = {
  items: T[];
  keyName: keyof T;
  striped?: boolean;
  children: (item: T) => ReactNode;
};

export const List = <T extends Record<string, unknown>>({
  items,
  keyName,
  striped,
  children,
}: ListProps<T>) => {
  return (
    <ul className={cn(css.list, { [css.striped]: striped })}>
      {items.map((item) => (
        <li key={String(item[keyName])} className={css.listItem}>
          {children(item)}
        </li>
      ))}
    </ul>
  );
};

// vue/src/components/List.vue
<script setup lang="ts" generic="T extends Record<string, unknown>">
defineProps<{
  items: T[];
  keyName: keyof T;
  striped?: boolean;
}>();
defineSlots<{
  row(props: { item: T }): any;
}>();
</script>

<template>
  <ul :class="['list', { striped }]">
    <template v-for="item in items" :key="item[keyName]">
      <li>
        <slot name="row" :item="item" />
      </li>
    </template>
  </ul>
</template>

<style scoped>
.list {
  li {
    padding: 0.25rem;
  }

  li+li {
    border-top: 1px solid #a1a1a1;
  }
}

.striped {
  li:nth-child(even) {
    background-color: #f8f9fa;
  }
}
</style>
