// vue/src/App.vue
<script setup lang="ts">
import Tab, { type TabConfig } from '@/components/Tab.vue';
import CounterPage from '@/pages/CounterPage.vue';
import FormPage from '@/pages/FormPage.vue';
import TodoList from '@/components/TodoList/TodoList.vue';
import ListPage from '@/pages/ListPage.vue';
import ComposablePage from './pages/ComposablePage.vue';

const tabs = [
  { title: 'Counter', content: CounterPage },
  { title: 'Form', content: FormPage },
  { title: 'Todo List', content: TodoList },
  { title: 'List', content: ListPage },
  { title: 'Composables', content: ComposablePage },
] as const satisfies TabConfig[];
</script>

<template>
  <Tab :tabs="tabs" />
</template>

// react/src/App.tsx
import { Tab } from "@/components/Tab";
import { Counter } from "@/pages/CounterPage";
import { FormPage } from "@/pages/FormPage";
import { TodoList } from "@/components/TodoList";
import { WrongListPage } from "@/pages/WrongListPage";
import { ListPage } from "@/pages/ListPage";
import { HookBkPage } from "@/pages/HookBkPage";
import { HookPage } from "@/pages/HookPage";

function App() {
  return (
    <>
      <Tab
        tabs={[
          {
            title: "Counter",
            content: <Counter />,
          },
          {
            title: "Form",
            content: <FormPage />,
          },
          {
            title: "Todo List",
            content: <TodoList />,
          },
          {
            title: "List(Wrong)",
            content: <WrongListPage />,
          },
          {
            title: "List",
            content: <ListPage />,
          },
          {
            title: "Hooks(BK)",
            content: <HookBkPage />,
          },
          {
            title: "Hooks",
            content: <HookPage />,
          },
        ]}
      />
    </>
  );
}

export default App;
