// vue/src/pages/CounterPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import Button from '@/components/Button.vue'

const count = ref(0)
const increment = () => count.value++
const decrement = () => count.value--
const double = computed(() => count.value * 2)
</script>

<template>
  <div>count: {{ count }}</div>
  <Button color="secondary" @click="increment">+</Button>
  <Button color="secondary" @click="decrement">-</Button>
  <div>count x2: {{ double }}</div>
  <div>count x3: {{ count * 3 }}</div>
</template>

// react/src/pages/CounterPage.tsx
import { useState } from "react";
import { Button } from "@/components/Button";

export const Counter = () => {
  const [count, setCount] = useState(0);
  const increment = () => setCount((prev) => prev + 1);
  const decrement = () => setCount((prev) => prev - 1);
  const double = count * 2;

  return (
    <>
      <div>count: {count}</div>
      <Button color="secondary" onClick={increment}>+</Button>
      <Button color="secondary" onClick={decrement}>-</Button>
      <div>count x2: {double}</div>
      <div>count x3: {count * 3}</div>
    </>
  );
};
